version: "3.8"

volumes:
  go-build:
  pg-data:

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go-build:/go/pkg/mod
    environment:
      - GIN_MODE=release
      - SMTP_HOST=mail
      - SMTP_PORT=1025
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:14.3
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=root
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
